# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [2]:
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [4]:
my_array = np.array([1,2,3,4])

In [7]:
print(my_array)

[1 2 3 4]


In [11]:
my_2D_array = np.array([[1,2,3,4],[5,6,7,8]])

In [12]:
print(my_2D_array)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
my_3D_array = np.array([[[1,2,3,4],[5,6,7,8]], [[1,2,3,4],[9,10,11,12]]])

In [14]:
print(my_3D_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [16]:
my_2D_array = np.array([[1,2,3,4],[5,6,7,8]])

In [17]:
# Print the no.of dimensions for the array
print(my_2D_array.ndim)

2


In [18]:
# Print the shape of the array as no. of rows and columns
print(my_2D_array.shape)

(2, 4)


In [19]:
# Print the size of the array
print(my_2D_array.size)

8


In [20]:
# Print the data type of the array
print(my_2D_array.dtype)

int32


In [21]:
# Print the number of items in the array
print(my_2D_array.itemsize)

4


In [22]:
# Print the data of the array
print(my_2D_array.data)

In [23]:
# Print the no. of bytes the array is consuming
print(my_2D_array.nbytes)

32


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [26]:
# Prints an array of 5 rows and 5 columns filled with zeroes
array1 = np.zeros((5, 5))

In [27]:
print(array1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
# Prints an array of 5 rows and 5 columns filled with ones
array2 = np.ones((5,5))

In [29]:
print(array2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [74]:
# Prints an array with 5 values without initializing entries
array3 = np.empty([5])

In [75]:
print(array3)

[0.56798287 0.73446938 0.60733759 0.40708234 0.71589752]


In [52]:
# Prints an array of 4 rows and 6 columns filled with 5 which is the given value
array4 = np.full((4,6),5)

In [53]:
print(array4)

[[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]]


In [55]:
# Prints the values between 0 and 20 at 3 intervals
array5 = np.arange(0,20,3)

In [56]:
print(array5)

[ 0  3  6  9 12 15 18]


In [57]:
# Prints five evenly spaced numbers between 2 and 3
array6 = np.linspace(2,3,5)

In [58]:
print(array6)

[2.   2.25 2.5  2.75 3.  ]


In [60]:
# Prints five random numbers between 0 and 1
array7 = np.random.random(5)

In [61]:
print(array7)

[0.56798287 0.73446938 0.60733759 0.40708234 0.71589752]


## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [76]:
# Define arrays:
a = np.ones((4,5))
b = np.random.random((4,5))

# Print the shapes of each array.
print(f"a shape: {a.shape}")
print(f"b shape: {b.shape}")

a shape: (4, 5)
b shape: (4, 5)


In [77]:
print(a)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0.74687002 0.14379336 0.91957372 0.90128391 0.35420598]
 [0.10929854 0.76091778 0.4380786  0.43611561 0.39184609]
 [0.47708605 0.69289695 0.37586812 0.35814803 0.017476  ]
 [0.33970218 0.72019316 0.88213096 0.06426791 0.77996888]]


In [79]:
print(a + b)
print(a - b)
print(a * b)

[[1.74687002 1.14379336 1.91957372 1.90128391 1.35420598]
 [1.10929854 1.76091778 1.4380786  1.43611561 1.39184609]
 [1.47708605 1.69289695 1.37586812 1.35814803 1.017476  ]
 [1.33970218 1.72019316 1.88213096 1.06426791 1.77996888]]
[[0.25312998 0.85620664 0.08042628 0.09871609 0.64579402]
 [0.89070146 0.23908222 0.5619214  0.56388439 0.60815391]
 [0.52291395 0.30710305 0.62413188 0.64185197 0.982524  ]
 [0.66029782 0.27980684 0.11786904 0.93573209 0.22003112]]
[[0.74687002 0.14379336 0.91957372 0.90128391 0.35420598]
 [0.10929854 0.76091778 0.4380786  0.43611561 0.39184609]
 [0.47708605 0.69289695 0.37586812 0.35814803 0.017476  ]
 [0.33970218 0.72019316 0.88213096 0.06426791 0.77996888]]


In [80]:
# Define arrays:
c = np.ones((3,4))
d = np.arange(4)

# Print the shapes of each array.
print(f"c shape: {c.shape}")
print(f"d shape: {d.shape}")

c shape: (3, 4)
d shape: (4,)


In [81]:
print(c)
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3]


In [82]:
print(c + d)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [102]:
# Define arrays:
e = np.ones((5,8))
f = np.arange(8)

# Print the shapes of each array.
print(f"e shape: {e.shape}")
print(f"f shape: {f.shape}")

e shape: (5, 8)
f shape: (8,)


In [103]:
print(e)
print(f)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[0 1 2 3 4 5 6 7]


In [104]:
print(e + f)

[[1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]]


## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [108]:
# Defining the arrays
a = np.arange(2,7)
b = np.arange(1,6)
c = np.arange(3,8)
d = np.arange(2,12, 2)

In [109]:
print(a)
print(b)
print(c)
print(d)

[2 3 4 5 6]
[1 2 3 4 5]
[3 4 5 6 7]
[ 2  4  6  8 10]


In [111]:
# sums the elements in array a
print(np.sum(a))

20


In [123]:
# compares b and c array and returns a new array with minimum values at each position 
print(np.minimum(b,c))

[1 2 3 4 5]


In [124]:
# compares b and d array and returns a new array with maximum values at each position
print(np.maximum(b,d))

[ 2  4  6  8 10]


In [115]:
# returns the arithmetic mean value of array d
print(np.mean(d))

6.0


In [116]:
# Prints the cumulative sum of the elements along the b array
print(np.cumsum(b))

[ 1  3  6 10 15]


In [117]:
# Returns Pearson product-moment correlation coefficients of c array
print(np.corrcoef(c))

1.0


In [118]:
# Prints the standard deviation along the c array
print(np.std(c))

1.4142135623730951


In [120]:
# Prints the variance along the a array
print(np.var(a))

2.0


## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [125]:
# Two lists of boolean values
a = [True, True, False, False]
b = [False, False, True, True]

In [126]:
# Perform a logical "or":
np.logical_or(a, b)

array([ True,  True,  True,  True])

In [127]:
# Perform a logical "and":
np.logical_and(a, b)

array([False, False, False, False])

In [130]:
# Perform a logical "not":
np.logical_not(a)

array([False, False,  True,  True])

In [131]:
# Perform a logical "not":
np.logical_not(b)

array([ True,  True, False, False])