# Lesson 2 Practice: NumPy Part 2
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L02-Numpy_Part2-Lesson.ipynb](./L02-Numpy_Part2-Lesson.ipynb).  


## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired. 

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [1]:
import numpy as np

## Task 2a: Indexing by Subsetting and Slicing

In the practice notebook perform the following:

1. Create (or re-use) 3 arrays, each containing three dimensions.
2. Slice each of these arrays so that:
    + One element / number is returned.
    + One dimension is returned.
    + A subset of a dimension is returned.
3. What is the difference between `[x:]` and `[x, ...]`? (hint, try each on high-dimension arrays).
    
*Exactly what you choose to return is not imporant at this point, the goal of this task is to train you so that if you are given an n-dimension NumPy array, you can write an index or slice that returns a subset of desired positions.*

In [2]:
a = np.array([[[1,2,3,4],[5,6,7,8]], [[1,2,3,4],[9,10,11,12]]])
b = np.array([[[1,3,5,7],[2,4,6,8]], [[1,3,5,7],[1,2,3,4]]])
c = np. array([[[0,2,4,8],[3,6,9,0]],[[2,4,6,8],[3,6,9,0]]])

In [3]:
print(a)
print(b)
print(c)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]
[[[1 3 5 7]
  [2 4 6 8]]

 [[1 3 5 7]
  [1 2 3 4]]]
[[[0 2 4 8]
  [3 6 9 0]]

 [[2 4 6 8]
  [3 6 9 0]]]


In [16]:
a[1:3]

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]]])

In [17]:
a[1,-2]

array([1, 2, 3, 4])

In [18]:
b[:4]

array([[[1, 3, 5, 7],
        [2, 4, 6, 8]],

       [[1, 3, 5, 7],
        [1, 2, 3, 4]]])

In [19]:
b[-1,-1]

array([1, 2, 3, 4])

In [20]:
c[1:]

array([[[2, 4, 6, 8],
        [3, 6, 9, 0]]])

In [25]:
c[1,-2]

array([2, 4, 6, 8])

## Task 3a: Boolean Indexing

In the practice notebook perform the following:

+ Experiment with the following boolean conditionals to generate boolean arrays for indexing:
  + Greater than
  + Less than
  + Equals
  + Combine two or more of the above with:
      + or `|`
      + and `&`

You can create arrays or use existing ones

In [37]:
# Create a 3 x 4 array of random numbers
d = np.random.random((3,4))
print(d)
# Find all values in the matrix less than 0.5
d < 0.5

[[0.82634159 0.79577339 0.85195262 0.78102861]
 [0.78528653 0.83945754 0.47280176 0.27083176]
 [0.66183301 0.78405867 0.91600417 0.02703831]]


array([[False, False, False, False],
       [False, False,  True,  True],
       [False, False, False,  True]])

In [38]:
d[d < 0.5]

array([0.47280176, 0.27083176, 0.02703831])

In [39]:
d > 0.5

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [ True,  True,  True, False]])

In [40]:
d[d > 0.5]

array([0.82634159, 0.79577339, 0.85195262, 0.78102861, 0.78528653,
       0.83945754, 0.66183301, 0.78405867, 0.91600417])

In [46]:
e = np.array([1,2,3,4])

In [47]:
e < 5

array([ True,  True,  True,  True])

In [52]:
e == 9

True

In [55]:
d == 0.47280176

False

In [67]:
d >= 0.2

True

In [68]:
d <= 0.2

False

## Task 4a: Getting Help

In the practice notebook perform the following:

+ In the code cell below, call `help()` on two of the following functions: `np.transpose()`, `np.reshape()`, `np.resize()`, `np.ravel()`, `np.append()`, `np.delete()`, `np.concatenate()`, `np.vstack()`, `np.hstack()`, `np.column_stack()`, `np.vsplit()`, `np.hsplit()` 
+ Respond to this question: Did you understand the help docuemntation? Could you use the function just by looking at what the help says about it?  

In [69]:
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Reverse or permute the axes of an array; returns the modified array.
    
    For an array a with two axes, transpose(a) gives the matrix transpose.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : tuple or list of ints, optional
        If specified, it must be a tuple or list which contains a permutation of
        [0,1,..,N-1] where N is the number of axes of a.  The i'th axis of the
        returned array will correspond to the axis numbered ``axes[i]`` of the
        input.  If not specified, defaults to ``range(a.ndim)[::-1]``, which
        reverses the order of the axes.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the

In [70]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equal or
   

## Task 5a: Transposing an Array

In the practice notebook perform the following:

+ Create a matrix of any size and transpose it.

In [71]:
m = np.random.random((3,4))

print(m)

print(np.transpose(m))


[[0.17699014 0.05804844 0.22013316 0.90558694]
 [0.43618034 0.57759838 0.72858981 0.2694615 ]
 [0.51660576 0.56349212 0.36239199 0.33856826]]
[[0.17699014 0.43618034 0.51660576]
 [0.05804844 0.57759838 0.56349212]
 [0.22013316 0.72858981 0.36239199]
 [0.90558694 0.2694615  0.33856826]]


## Task 5b: Reshaping an Array

In the practice notebook peform the following:

+ Create a matrix and resize it by adding 2 extra columns
+ Create a matrix and resize it by adding 1 extra row
+ Create a matrix of 8 x 2 and resize it to 4 x 4

In [73]:
x = np.array([[1,2,3,4],[5,6,7,8]])
print(x.shape)

(2, 4)


In [74]:
# Resize `x` to ((2,6))
np.resize(x, (2,6))

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 1, 2, 3, 4]])

In [75]:
# Resize `x` to ((3,4))
np.resize(x, (3,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [77]:
y = np.random.random((8,2))
print(y)
print(y.shape)

[[0.51670776 0.49892986]
 [0.29049747 0.57395857]
 [0.42335864 0.83431299]
 [0.02086938 0.08522561]
 [0.78962746 0.57876788]
 [0.62485919 0.68990795]
 [0.68722232 0.2310257 ]
 [0.15181734 0.83184833]]
(8, 2)


In [79]:
print(y.reshape((4,4)))

[[0.51670776 0.49892986 0.29049747 0.57395857]
 [0.42335864 0.83431299 0.02086938 0.08522561]
 [0.78962746 0.57876788 0.62485919 0.68990795]
 [0.68722232 0.2310257  0.15181734 0.83184833]]


## Task 5c: Appending to an Array

In the practice notebook perform the following:

 + Create a three dimensional array and append another row to the array
 + Append another colum to the array
 + Print the final results

In [93]:
my_3D_array = np.array([[[1,2,3,4],[5,6,7,8]], [[11,12,13,14],[9,10,11,12]]])
print(my_3D_array)
new_array = np.append(my_3D_array, [[[10,12,14,16],[11,14,12,18]], [[12,16,18,20],[13,15,17,19]]], axis=1)
print(new_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [ 9 10 11 12]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [10 12 14 16]
  [11 14 12 18]]

 [[11 12 13 14]
  [ 9 10 11 12]
  [12 16 18 20]
  [13 15 17 19]]]


In [103]:
new_array2 = np.append(new_array, [[10,12,14,16], [12,16,18,20], [11,13,15,17]], axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

In [109]:
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
array1 = np.append(my_2d_array, [[7], [8]], axis=1)
print(array1)
array2 = np.append(array1, [[2], [4], [6], [8], [4]], axis=0)

print(array2)

[[1 2 3 4 7]
 [5 6 7 8 8]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 1

## Task 5d: Inserting and Deleting Elements

In the practice notebook perform the following:

+ Examine the `help()` documentation for how to use the `insert()` and `delete()` functions.
+ Create a matrix and practice inserting a row and deleting a column.

In [114]:
help(np.insert)

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

In [115]:
help(np.delete)

Help on function delete in module numpy:

delete(arr, obj, axis=None)
    Return a new array with sub-arrays along an axis deleted. For a one
    dimensional array, this returns those entries not returned by
    `arr[obj]`.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : slice, int or array of ints
        Indicate indices of sub-arrays to remove along the specified axis.
    
        .. versionchanged:: 1.19.0
            Boolean indices are now treated as a mask of elements to remove,
            rather than being cast to the integers 0 and 1.
    
    axis : int, optional
        The axis along which to delete the subarray defined by `obj`.
        If `axis` is None, `obj` is applied to the flattened array.
    
    Returns
    -------
    out : ndarray
        A copy of `arr` with the elements specified by `obj` removed. Note
        that `delete` does not occur in-place. If `axis` is None, `out` is
        a flattened array.
    
    See Also

In [117]:
m = np.array([2,4,6,8,10,12,14,16,18])

In [119]:
n = np.insert(m, 3, 100)
print(n)

[  2   4   6 100   8  10  12  14  16  18]


In [121]:
p = np.delete(m, 4)
print(p)

[ 2  4  6  8 12 14 16 18]


## Task 5e: Joining Arrays

In the practice notebook perform the following:

+ Execute the code (in the cell below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [122]:
# Concatentate `my_array` and `x`: similar to np.append()
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
print(np.concatenate((my_array, x)))

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
print(np.vstack((my_array, my_2d_array)))

# Stack arrays horizontally
print("\nhstack:")
print(np.hstack((my_2d_array, my_2d_array)))

# Stack arrays column-wise
print("\ncolumn_stack:")
print(np.column_stack((my_2d_array, my_2d_array)))

concatenate:
[1 2 3 4 1 1 1 1]

vstack:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]

hstack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]

column_stack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


## Task 5d: Splitting Arrays

In the practice notebook perform the following:

+ Execute the code (as shown below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [123]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
print(np.hsplit(my_2d_array, 2))

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
print(np.vsplit(my_2d_array, 2))

original:
[[1 2 3 4]
 [5 6 7 8]]

hsplit:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

vsplit:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
